language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --no-interaction

before_script:
  # - mkdir -p build/coverage

script:
  - php vendor/bin/phpunit

notifications:
  email:
    - gulturyan@gmail.com